<a href="https://colab.research.google.com/github/vandat2614/Learn-PyTorch/blob/main/Exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.shape

(tensor([[0.7975, 0.7819, 0.8007, 0.2778, 0.7429, 0.0580, 0.5249],
         [0.7179, 0.4512, 0.5160, 0.2759, 0.1995, 0.2336, 0.7783],
         [0.1039, 0.7769, 0.3810, 0.7356, 0.1563, 0.6482, 0.9796],
         [0.6410, 0.1597, 0.2726, 0.7934, 0.5577, 0.7094, 0.6181],
         [0.1516, 0.2977, 0.2805, 0.5059, 0.1129, 0.6287, 0.7365],
         [0.7147, 0.7647, 0.1078, 0.2386, 0.4013, 0.4594, 0.8603],
         [0.0407, 0.2693, 0.8217, 0.9462, 0.0904, 0.6048, 0.7296]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random2_tensor = torch.rand(size=(1, 7))

# Perform matrix multiplication
result = torch.matmul(random_tensor, random2_tensor.T)
result, result.shape

(tensor([[2.2200],
         [1.8518],
         [1.8120],
         [2.3206],
         [1.3666],
         [2.0106],
         [1.7047]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(26012004)

# Create two random tensors
first_tensor = torch.rand(size=(7, 7))
second_tensor = torch.rand(size=(1, 7))

# Matrix multiply tensors
result = torch.matmul(first_tensor, second_tensor.T)
result, result.shape

(tensor([[2.0848],
         [1.1397],
         [1.6449],
         [1.9130],
         [2.3880],
         [2.4546],
         [1.6131]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

# Set seed for GPU to ensure that computations (e.g., neural network training)
# produce the same results every time the code is run (reproducibility).


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU
first_tensor = torch.rand(size=(2, 3)).to(device)
second_tensor = torch.rand(size=(2, 3)).to(device)

first_tensor, second_tensor, first_tensor.device, second_tensor.device

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'),
 device(type='cuda', index=0),
 device(type='cuda', index=0))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(first_tensor, second_tensor.T)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
result.max(), result.min()
# Find min


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print(f'Max index: {result.argmax()}')

# Find arg min
print(f'Min index: {result.argmin()}')


Max index: 3
Min index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
first_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
second_tensor = first_tensor.squeeze()

# Print out tensors and their shapes
print(f"First tensor")
print(first_tensor)
print(first_tensor.shape)
print()

print(f"Second tensor")
print(second_tensor)
print(second_tensor.shape)
print()

First tensor
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])

Second tensor
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])

